.TH circuits.sniff 1 "Jun 2011" "circuits 1.7dev" "User Commands"
.SH NAME
circuits.sniff \- event sniffer of the circuits library
.SH SYNOPSIS
.B circuits.sniff
[\fIoptions\fR]
.SH DESCRIPTION
circuits.sniff is an event sniffing tool. It can be used to sniff and debug
Events as they occur in another system. As long as that system has an instance
of the Bridge Component, events can be sniffed and printed.
.SH OPTIONS
.TP
\fB-b\fR \fIaddress:port\fR
Bind to address:port. Default address is 0.0.0.0:8000.
.TP
\fB--version\fR
Output version information and exit.
.SH AUTHOR
James Mills <prologic@shortcircuit.net.au>
.PP
This manual page was written by Daniele Tricoli <eriol@mornie.org>, for the
Debian project (but may be used by others).
