#!/usr/bin/env python

import os
import sys

from traclib import Trac

def main():
    opts = object()
    trac = Trac(opts)
    files = [x for x in os.listdir(os.getcwd()) if x.endswith(".wiki")]
    for file in files:
        page, _ = os.path.splitext(file)
        page = page.replace("_", "/")

        sys.stdout.write("Sycning %s ... " % page)
        sys.stdout.flush()
        trac.save(page)
        print "DONE"

if __name__ == "__main__":
    main()
