name: Manual PyPI Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.2.0)"
        required: true
  # push:
  #   branches:
  #     - master

# permissions:
#   id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Install build dependencies
        run: pip install build

      - |
        python - <<'EOF'
        from pathlib import Path

        readme = Path("README.rst").read_text()
        examples = Path("examples/index.rst").read_text()

        combined = readme.replace(
            ".. include:: examples/index.rst",
            examples
        )

        Path("README_full.rst").write_text(combined)
        EOF

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
